// Code generated by MockGen. DO NOT EDIT.
// Source: models.go
//
// Generated by this command:
//
//	mockgen -source=models.go -destination=mocks/commandRunner_mock.go -package=commandRunner_mock
//

// Package commandRunner_mock is a generated GoMock package.
package commandRunner_mock

import (
	commandRunner "comp7705/containerScanner/internal/commandRunner"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// RunCommand mocks base method.
func (m *MockCommandRunner) RunCommand(command string, args []string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCommand", command, args)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunCommand indicates an expected call of RunCommand.
func (mr *MockCommandRunnerMockRecorder) RunCommand(command, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCommand", reflect.TypeOf((*MockCommandRunner)(nil).RunCommand), command, args)
}

// MockPackageHelperFunctionCollection is a mock of PackageHelperFunctionCollection interface.
type MockPackageHelperFunctionCollection struct {
	ctrl     *gomock.Controller
	recorder *MockPackageHelperFunctionCollectionMockRecorder
	isgomock struct{}
}

// MockPackageHelperFunctionCollectionMockRecorder is the mock recorder for MockPackageHelperFunctionCollection.
type MockPackageHelperFunctionCollectionMockRecorder struct {
	mock *MockPackageHelperFunctionCollection
}

// NewMockPackageHelperFunctionCollection creates a new mock instance.
func NewMockPackageHelperFunctionCollection(ctrl *gomock.Controller) *MockPackageHelperFunctionCollection {
	mock := &MockPackageHelperFunctionCollection{ctrl: ctrl}
	mock.recorder = &MockPackageHelperFunctionCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageHelperFunctionCollection) EXPECT() *MockPackageHelperFunctionCollectionMockRecorder {
	return m.recorder
}

// NewCommandRunner mocks base method.
func (m *MockPackageHelperFunctionCollection) NewCommandRunner() commandRunner.CommandRunner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCommandRunner")
	ret0, _ := ret[0].(commandRunner.CommandRunner)
	return ret0
}

// NewCommandRunner indicates an expected call of NewCommandRunner.
func (mr *MockPackageHelperFunctionCollectionMockRecorder) NewCommandRunner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCommandRunner", reflect.TypeOf((*MockPackageHelperFunctionCollection)(nil).NewCommandRunner))
}
