FROM node:22.22.1-alpine3.23 AS s0builder

WORKDIR /build

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json ./
COPY tsconfig.test.json ./
COPY jest.config.cjs ./
RUN npm ci
COPY src src
COPY __tests__ __tests__
COPY __testResources__ __testResources__

RUN npm run compile
RUN npm run test

FROM node:22.22.1-alpine3.23 AS s1runtime

WORKDIR /app

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci --omit=dev

COPY --from=s0builder /build/dist /app/dist

RUN chown -R node:node /app
USER node:node

EXPOSE 9080

CMD ["npm", "run", "start"]