import { CisaDecisionTableRowSchema } from './types.js';

/**
 * CERT `cisa_coordinator_2_0_3` decision table (36 rows).
 * Authoritative for CISA outcomes.
 */
export const CISA_COORDINATOR_2_0_3_TABLE = [
    {
        rowIndex: 0,
        exploitation: 'none',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 1,
        exploitation: 'none',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'medium',
        outcome: 'Track',
    },
    {
        rowIndex: 2,
        exploitation: 'none',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'high',
        outcome: 'Track',
    },
    {
        rowIndex: 3,
        exploitation: 'none',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 4,
        exploitation: 'none',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'medium',
        outcome: 'Track',
    },
    {
        rowIndex: 5,
        exploitation: 'none',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'high',
        outcome: 'Track*',
    },
    {
        rowIndex: 6,
        exploitation: 'none',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 7,
        exploitation: 'none',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'medium',
        outcome: 'Track',
    },
    {
        rowIndex: 8,
        exploitation: 'none',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'high',
        outcome: 'Attend',
    },
    {
        rowIndex: 9,
        exploitation: 'none',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 10,
        exploitation: 'none',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'medium',
        outcome: 'Track',
    },
    {
        rowIndex: 11,
        exploitation: 'none',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'high',
        outcome: 'Attend',
    },
    {
        rowIndex: 12,
        exploitation: 'public poc',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 13,
        exploitation: 'public poc',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'medium',
        outcome: 'Track',
    },
    {
        rowIndex: 14,
        exploitation: 'public poc',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'high',
        outcome: 'Track*',
    },
    {
        rowIndex: 15,
        exploitation: 'public poc',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 16,
        exploitation: 'public poc',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'medium',
        outcome: 'Track*',
    },
    {
        rowIndex: 17,
        exploitation: 'public poc',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'high',
        outcome: 'Attend',
    },
    {
        rowIndex: 18,
        exploitation: 'public poc',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 19,
        exploitation: 'public poc',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'medium',
        outcome: 'Track',
    },
    {
        rowIndex: 20,
        exploitation: 'public poc',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'high',
        outcome: 'Attend',
    },
    {
        rowIndex: 21,
        exploitation: 'public poc',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 22,
        exploitation: 'public poc',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'medium',
        outcome: 'Track*',
    },
    {
        rowIndex: 23,
        exploitation: 'public poc',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'high',
        outcome: 'Attend',
    },
    {
        rowIndex: 24,
        exploitation: 'active',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 25,
        exploitation: 'active',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'medium',
        outcome: 'Track',
    },
    {
        rowIndex: 26,
        exploitation: 'active',
        automatable: 'no',
        technicalImpact: 'partial',
        missionImpact: 'high',
        outcome: 'Attend',
    },
    {
        rowIndex: 27,
        exploitation: 'active',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'low',
        outcome: 'Track',
    },
    {
        rowIndex: 28,
        exploitation: 'active',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'medium',
        outcome: 'Attend',
    },
    {
        rowIndex: 29,
        exploitation: 'active',
        automatable: 'no',
        technicalImpact: 'total',
        missionImpact: 'high',
        outcome: 'Act',
    },
    {
        rowIndex: 30,
        exploitation: 'active',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'low',
        outcome: 'Attend',
    },
    {
        rowIndex: 31,
        exploitation: 'active',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'medium',
        outcome: 'Attend',
    },
    {
        rowIndex: 32,
        exploitation: 'active',
        automatable: 'yes',
        technicalImpact: 'partial',
        missionImpact: 'high',
        outcome: 'Act',
    },
    {
        rowIndex: 33,
        exploitation: 'active',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'low',
        outcome: 'Attend',
    },
    {
        rowIndex: 34,
        exploitation: 'active',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'medium',
        outcome: 'Act',
    },
    {
        rowIndex: 35,
        exploitation: 'active',
        automatable: 'yes',
        technicalImpact: 'total',
        missionImpact: 'high',
        outcome: 'Act',
    },
] as const;

CisaDecisionTableRowSchema.array().length(36).parse(CISA_COORDINATOR_2_0_3_TABLE);
