// Code generated by MockGen. DO NOT EDIT.
// Source: models.go
//
// Generated by this command:
//
//	mockgen -source=models.go -destination=mocks/trivyReportParser_mock.go -package=trivyReportParser_mock
//

// Package trivyReportParser_mock is a generated GoMock package.
package trivyReportParser_mock

import (
	trivyReportParser "comp7705/containerScanner/internal/trivyReportParser"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTrivyReportParser is a mock of TrivyReportParser interface.
type MockTrivyReportParser struct {
	ctrl     *gomock.Controller
	recorder *MockTrivyReportParserMockRecorder
	isgomock struct{}
}

// MockTrivyReportParserMockRecorder is the mock recorder for MockTrivyReportParser.
type MockTrivyReportParserMockRecorder struct {
	mock *MockTrivyReportParser
}

// NewMockTrivyReportParser creates a new mock instance.
func NewMockTrivyReportParser(ctrl *gomock.Controller) *MockTrivyReportParser {
	mock := &MockTrivyReportParser{ctrl: ctrl}
	mock.recorder = &MockTrivyReportParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrivyReportParser) EXPECT() *MockTrivyReportParserMockRecorder {
	return m.recorder
}

// ParseTrivyReport mocks base method.
func (m *MockTrivyReportParser) ParseTrivyReport(fileData []byte) (trivyReportParser.TrivyReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseTrivyReport", fileData)
	ret0, _ := ret[0].(trivyReportParser.TrivyReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseTrivyReport indicates an expected call of ParseTrivyReport.
func (mr *MockTrivyReportParserMockRecorder) ParseTrivyReport(fileData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseTrivyReport", reflect.TypeOf((*MockTrivyReportParser)(nil).ParseTrivyReport), fileData)
}

// MockPackageHelperFunctionCollection is a mock of PackageHelperFunctionCollection interface.
type MockPackageHelperFunctionCollection struct {
	ctrl     *gomock.Controller
	recorder *MockPackageHelperFunctionCollectionMockRecorder
	isgomock struct{}
}

// MockPackageHelperFunctionCollectionMockRecorder is the mock recorder for MockPackageHelperFunctionCollection.
type MockPackageHelperFunctionCollectionMockRecorder struct {
	mock *MockPackageHelperFunctionCollection
}

// NewMockPackageHelperFunctionCollection creates a new mock instance.
func NewMockPackageHelperFunctionCollection(ctrl *gomock.Controller) *MockPackageHelperFunctionCollection {
	mock := &MockPackageHelperFunctionCollection{ctrl: ctrl}
	mock.recorder = &MockPackageHelperFunctionCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageHelperFunctionCollection) EXPECT() *MockPackageHelperFunctionCollectionMockRecorder {
	return m.recorder
}

// NewTrivyReportParser mocks base method.
func (m *MockPackageHelperFunctionCollection) NewTrivyReportParser() trivyReportParser.TrivyReportParser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTrivyReportParser")
	ret0, _ := ret[0].(trivyReportParser.TrivyReportParser)
	return ret0
}

// NewTrivyReportParser indicates an expected call of NewTrivyReportParser.
func (mr *MockPackageHelperFunctionCollectionMockRecorder) NewTrivyReportParser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTrivyReportParser", reflect.TypeOf((*MockPackageHelperFunctionCollection)(nil).NewTrivyReportParser))
}
