// Code generated by MockGen. DO NOT EDIT.
// Source: models.go
//
// Generated by this command:
//
//	mockgen -source=models.go -destination=mocks/adder_mock.go -package=adder_mock
//

// Package adder_mock is a generated GoMock package.
package adder_mock

import (
	adder "comp7705/containerScanner/internal/adder"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdder is a mock of Adder interface.
type MockAdder struct {
	ctrl     *gomock.Controller
	recorder *MockAdderMockRecorder
	isgomock struct{}
}

// MockAdderMockRecorder is the mock recorder for MockAdder.
type MockAdderMockRecorder struct {
	mock *MockAdder
}

// NewMockAdder creates a new mock instance.
func NewMockAdder(ctrl *gomock.Controller) *MockAdder {
	mock := &MockAdder{ctrl: ctrl}
	mock.recorder = &MockAdderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdder) EXPECT() *MockAdderMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockAdder) Add() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add")
	ret0, _ := ret[0].(int)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockAdderMockRecorder) Add() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockAdder)(nil).Add))
}

// GetA mocks base method.
func (m *MockAdder) GetA() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetA")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetA indicates an expected call of GetA.
func (mr *MockAdderMockRecorder) GetA() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetA", reflect.TypeOf((*MockAdder)(nil).GetA))
}

// GetB mocks base method.
func (m *MockAdder) GetB() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetB")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetB indicates an expected call of GetB.
func (mr *MockAdderMockRecorder) GetB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetB", reflect.TypeOf((*MockAdder)(nil).GetB))
}

// SetA mocks base method.
func (m *MockAdder) SetA(a int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetA", a)
}

// SetA indicates an expected call of SetA.
func (mr *MockAdderMockRecorder) SetA(a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetA", reflect.TypeOf((*MockAdder)(nil).SetA), a)
}

// SetB mocks base method.
func (m *MockAdder) SetB(b int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetB", b)
}

// SetB indicates an expected call of SetB.
func (mr *MockAdderMockRecorder) SetB(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetB", reflect.TypeOf((*MockAdder)(nil).SetB), b)
}

// MockPackageHelperFunctionCollection is a mock of PackageHelperFunctionCollection interface.
type MockPackageHelperFunctionCollection struct {
	ctrl     *gomock.Controller
	recorder *MockPackageHelperFunctionCollectionMockRecorder
	isgomock struct{}
}

// MockPackageHelperFunctionCollectionMockRecorder is the mock recorder for MockPackageHelperFunctionCollection.
type MockPackageHelperFunctionCollectionMockRecorder struct {
	mock *MockPackageHelperFunctionCollection
}

// NewMockPackageHelperFunctionCollection creates a new mock instance.
func NewMockPackageHelperFunctionCollection(ctrl *gomock.Controller) *MockPackageHelperFunctionCollection {
	mock := &MockPackageHelperFunctionCollection{ctrl: ctrl}
	mock.recorder = &MockPackageHelperFunctionCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageHelperFunctionCollection) EXPECT() *MockPackageHelperFunctionCollectionMockRecorder {
	return m.recorder
}

// NewAdder mocks base method.
func (m *MockPackageHelperFunctionCollection) NewAdder() adder.Adder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAdder")
	ret0, _ := ret[0].(adder.Adder)
	return ret0
}

// NewAdder indicates an expected call of NewAdder.
func (mr *MockPackageHelperFunctionCollectionMockRecorder) NewAdder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAdder", reflect.TypeOf((*MockPackageHelperFunctionCollection)(nil).NewAdder))
}

// NewAdderWithA mocks base method.
func (m *MockPackageHelperFunctionCollection) NewAdderWithA(A int) adder.Adder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAdderWithA", A)
	ret0, _ := ret[0].(adder.Adder)
	return ret0
}

// NewAdderWithA indicates an expected call of NewAdderWithA.
func (mr *MockPackageHelperFunctionCollectionMockRecorder) NewAdderWithA(A any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAdderWithA", reflect.TypeOf((*MockPackageHelperFunctionCollection)(nil).NewAdderWithA), A)
}

// NewAdderWithAAndB mocks base method.
func (m *MockPackageHelperFunctionCollection) NewAdderWithAAndB(A, B int) adder.Adder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAdderWithAAndB", A, B)
	ret0, _ := ret[0].(adder.Adder)
	return ret0
}

// NewAdderWithAAndB indicates an expected call of NewAdderWithAAndB.
func (mr *MockPackageHelperFunctionCollectionMockRecorder) NewAdderWithAAndB(A, B any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAdderWithAAndB", reflect.TypeOf((*MockPackageHelperFunctionCollection)(nil).NewAdderWithAAndB), A, B)
}

// NewAdderWithB mocks base method.
func (m *MockPackageHelperFunctionCollection) NewAdderWithB(B int) adder.Adder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAdderWithB", B)
	ret0, _ := ret[0].(adder.Adder)
	return ret0
}

// NewAdderWithB indicates an expected call of NewAdderWithB.
func (mr *MockPackageHelperFunctionCollectionMockRecorder) NewAdderWithB(B any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAdderWithB", reflect.TypeOf((*MockPackageHelperFunctionCollection)(nil).NewAdderWithB), B)
}
