// Code generated by MockGen. DO NOT EDIT.
// Source: models.go
//
// Generated by this command:
//
//	mockgen -source=models.go -destination=mocks/runTrivy_mock.go -package=runTrivy_mock
//

// Package runTrivy_mock is a generated GoMock package.
package runTrivy_mock

import (
	commandRunner "comp7705/containerScanner/internal/commandRunner"
	runTrivy "comp7705/containerScanner/internal/runTrivy"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRunTrivy is a mock of RunTrivy interface.
type MockRunTrivy struct {
	ctrl     *gomock.Controller
	recorder *MockRunTrivyMockRecorder
	isgomock struct{}
}

// MockRunTrivyMockRecorder is the mock recorder for MockRunTrivy.
type MockRunTrivyMockRecorder struct {
	mock *MockRunTrivy
}

// NewMockRunTrivy creates a new mock instance.
func NewMockRunTrivy(ctrl *gomock.Controller) *MockRunTrivy {
	mock := &MockRunTrivy{ctrl: ctrl}
	mock.recorder = &MockRunTrivyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunTrivy) EXPECT() *MockRunTrivyMockRecorder {
	return m.recorder
}

// RunTrivy_Filesystem_JsonScan mocks base method.
func (m *MockRunTrivy) RunTrivy_Filesystem_JsonScan(filesystemPath, outputFilePath string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTrivy_Filesystem_JsonScan", filesystemPath, outputFilePath)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTrivy_Filesystem_JsonScan indicates an expected call of RunTrivy_Filesystem_JsonScan.
func (mr *MockRunTrivyMockRecorder) RunTrivy_Filesystem_JsonScan(filesystemPath, outputFilePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTrivy_Filesystem_JsonScan", reflect.TypeOf((*MockRunTrivy)(nil).RunTrivy_Filesystem_JsonScan), filesystemPath, outputFilePath)
}

// RunTrivy_Image_JsonScan mocks base method.
func (m *MockRunTrivy) RunTrivy_Image_JsonScan(imagePath, outputFilePath string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunTrivy_Image_JsonScan", imagePath, outputFilePath)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunTrivy_Image_JsonScan indicates an expected call of RunTrivy_Image_JsonScan.
func (mr *MockRunTrivyMockRecorder) RunTrivy_Image_JsonScan(imagePath, outputFilePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunTrivy_Image_JsonScan", reflect.TypeOf((*MockRunTrivy)(nil).RunTrivy_Image_JsonScan), imagePath, outputFilePath)
}

// MockPackageHelperFunctionCollection is a mock of PackageHelperFunctionCollection interface.
type MockPackageHelperFunctionCollection struct {
	ctrl     *gomock.Controller
	recorder *MockPackageHelperFunctionCollectionMockRecorder
	isgomock struct{}
}

// MockPackageHelperFunctionCollectionMockRecorder is the mock recorder for MockPackageHelperFunctionCollection.
type MockPackageHelperFunctionCollectionMockRecorder struct {
	mock *MockPackageHelperFunctionCollection
}

// NewMockPackageHelperFunctionCollection creates a new mock instance.
func NewMockPackageHelperFunctionCollection(ctrl *gomock.Controller) *MockPackageHelperFunctionCollection {
	mock := &MockPackageHelperFunctionCollection{ctrl: ctrl}
	mock.recorder = &MockPackageHelperFunctionCollectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageHelperFunctionCollection) EXPECT() *MockPackageHelperFunctionCollectionMockRecorder {
	return m.recorder
}

// NewRunTrivy mocks base method.
func (m *MockPackageHelperFunctionCollection) NewRunTrivy(arg0 commandRunner.CommandRunner) runTrivy.RunTrivy {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRunTrivy", arg0)
	ret0, _ := ret[0].(runTrivy.RunTrivy)
	return ret0
}

// NewRunTrivy indicates an expected call of NewRunTrivy.
func (mr *MockPackageHelperFunctionCollectionMockRecorder) NewRunTrivy(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRunTrivy", reflect.TypeOf((*MockPackageHelperFunctionCollection)(nil).NewRunTrivy), arg0)
}
