FROM node:22.22.1-alpine3.23 AS s0builder

WORKDIR /build

COPY applications/dashboard/help-content-draft help-content-draft
COPY applications/dashboard/public public
COPY applications/dashboard/src src
COPY applications/dashboard/eslint.config.js eslint.config.js
COPY applications/dashboard/index.html index.html
COPY applications/dashboard/package.json package.json
COPY applications/dashboard/package-lock.json package-lock.json
COPY applications/dashboard/tsconfig.app.json tsconfig.app.json
COPY applications/dashboard/tsconfig.json tsconfig.json
COPY applications/dashboard/tsconfig.node.json tsconfig.node.json
COPY applications/dashboard/vite.config.ts vite.config.ts
COPY applications/dashboard/vite.server.env vite.server.env

RUN npm ci
RUN npm run build

FROM nginx:1.29.4-alpine3.23 AS s1runtime

COPY --from=s0builder --chown=nginx:nginx /build/dist /fs-root/dashboard
COPY reverseProxy/nginx.conf /etc/nginx/nginx.conf

RUN nginx -t

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]